### ISSUE TITLE
"Cano" Command 

### ISSUE THREAD

**Issue by Clo612** [CobbCoding1/Cano#76]
@CobbCoding1 I think you should add a cano command so you do not have to stay in the Cano dirrectory and you can just type "Cano <filename>" and not "cd Cano" and then "./build/cano <filename>". This should be added in the future.

**Comment by CobbCoding1** [comment]
You can do this now, if you navigate to the cano source directory, and type make install (instead of just make), and this will install cano on your system. There are also build scripts (such as ./debian-install.sh) for installing on different types of systems.

This is of course assuming that I don't misunderstand your post. If so then let me know.

**Comment by Clo612** [comment]
@CobbCoding1 I am saying If for example you type "cano text.txt" and it opens up the text editor rather than going to the Cano directory "cd Cano" and then typing "./build/Cano text.txt" Instead then in any directory you can just type "Cano text.txt" I have an example attached.
![Screenshot 2024-06-05 7 41 00 PM](https://github.com/CobbCoding1/Cano/assets/105884295/58cb580e-8895-45ed-9d54-2afe0fb0465e)

**Comment by CobbCoding1** [comment]
yes, to get this functionality it needs to be accessible on your system's PATH. You can get this by installing it on your system, using either `make install` or using one of the installation methods (not just building it) laid out in the README.

**Comment by Clo612** [comment]
You should make it pre made already installed, for those who don't wanna go through the work.

**Comment by CobbCoding1** [comment]
I can't install it on your system unless you install it.

**Comment by Clo612** [comment]
I am just going to mark this issue closed and work on my own fix. Maybe even present it to you.
